server:
  servlet:
    context-path: /system
  port: 63110
#微服务配置
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher #解决高版本SpringBoot整合Swagger报错问题
  application:
    name: system-api
  datasource:
    username: root
    password: "0531"
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xuecheng_system?useUnicode=true&useSSL=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    hikari:
      minimum-idle: 5
      max-lifetime: 1800000
      maximum-pool-size: 10
      auto-commit: true
      connection-test-query: SELECT 1
# 日志文件配置路径
#logging:
#  config: classpath:log4j2.xml
logging:
  level:
    com.jiuxiao: debug
# knife4j文档配置
knife4j:
  enable: true
  openapi:
    title: 学成教育文档
    description: 学成在线系统管理接口文档
    email: fanye814@gmail.com
    concat: 悟道九霄
    version: v1.0
    license: Apache 2.0

