### 查询所有课程列表
POST {{content_port}}/content/course/list
Content-Type: application/json

{
  "currentPageNum": 1,
  "pageSize": 10,
  "courseName": "",
  "auditStatus": "",
  "courseType": "",
  "publishStatus": "203002"
}


### 查询所有课程分类
GET {{content_port}}/content/course-category/tree-nodes
Content-Type: application/json


### 新增课程信息
POST {{content_port}}/content/course
Content-Type: application/json

{
  "name": "游戏开发",
  "users": "高级人员",
  "tags": "游戏,Java,开发",
  "mt": "",
  "st": "",
  "grade": "204001",
  "teachmode": "200002",
  "description": "Java开发者的入门级小游戏",
  "pic": "",
  "charge": "201001",
  "price": 108,
  "originalPrice": 588,
  "qq": "1111222",
  "wechat": "qwerty",
  "phone": "18312345678",
  "validDays": 365
}


### 根据ID获取课程基本、营销信息
GET {{content_port}}/content/course/144
Content-Type: application/json


### 根据课程ID修改课程基本信息、营销信息
PUT {{content_port}}/content/course
Content-Type: application/json

{
  "id": 144,
  "name": "Redis入土",
  "users": "中级人员",
  "tags": "中间件,Java,开发",
  "mt": "1-3",
  "st": "1-3-2",
  "grade": "204001",
  "teachmode": "200002",
  "description": "中间件必须内容",
  "pic": "",
  "charge": "201001",
  "price": 98,
  "originalPrice": 120,
  "qq": "123456",
  "wechat": "8549865",
  "phone": "18700001111",
  "validDays": 205
}